### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by plkumjorn** [CSAILVision/NetDissect-Lite#10]
Hi,

Thank you for making your codes available online.

I try running the main.py on resnet18. Specifying FEATURE_NAMES = ['layer4'] in the settings file, everything works well. However, when I change it to  ['layer3'] and  ['layer2'], the terminal shows 'Bus error' after printing the line 'extracting feature from batch 256 / 495' and 'extracting feature from batch 129 / 495', respectively, and then the process terminates.

Would you please suggest me how I can solve this issue? Thank you.

Best,
Peter

**Comment by cjbarb7** [comment]
I encountered that and it looked like I ran out of space given the .mmap that was being created. Have you checked that you ran out of hard drive space when going to 'layer2', I know for 'layer1', the .mmap that was created took 1.6TB?

**Comment by PaulZhangIsing** [comment]
This is because it is draining out of your disk space. Probably you need to store it somewhere else

**Comment by plkumjorn** [comment]
I see. Thank you for your suggestions.
