### ISSUE TITLE
Cannot access datasets

### ISSUE THREAD

**Issue by jiangwh93** [CSAILVision/NetDissect-Lite#4]
Hi there, when I was downloading the BRODEN dataset as your instruction mentioned, I got "Connection refused" error. Neither can I visit the http://netdissect.csail.mit.edu project page for further information. Is there any other way to get these data and pre-trained models?

**Comment by sunyiyou** [comment]
I think the website is in the normal state. So plz check your web setting to work out this issue.

**Comment by jiangwh93** [comment]
It's working again. Thx!
