### ISSUE TITLE
How to use Densenet model ?

### ISSUE THREAD

**Issue by snorlaxse** [CSAILVision/NetDissect-Lite#6]
I modify the settings.py (MODEL = 'densenet161')  and download the whole_densenet161_places365_python36.pth.tar.   And run 'main.py'  import errors as below:
```
AttributeError: 'BatchNorm2d' object has no attribute 'track_running_stats'
```

**Comment by snorlaxse** [comment]
sorry, the issuse same as #3

**Comment by pipixia-bit** [comment]
hello, where can you find the  whole_densenet161_places365_python36.pth.tar
